# Publish Mathematics.NET NuGet Packages

name: Publish NuGet Packages
on:
  workflow_dispatch:

jobs:
  build-and-pack:
    name: Build and Pack NuGet Packages
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [ Mathematics.NET, Mathematics.NET.SourceGenerators ]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6

    - name: Set up .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          9.x
          10.x

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build ${{ matrix.project }}
      working-directory: src/${{ matrix.project }}
      run: dotnet build --configuration Release --no-restore

    - name: Create Packages Directory
      run: mkdir -p ${{ env.PACKAGES_DIR }}

    - name: Set Package Version
      id: get_version
      run: |
        TAG_NAME="${{ github.ref_name }}"
        VERSION=${TAG_NAME#v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Pack ${{ matrix.project }}
      working-directory: src/${{ matrix.project }}
      run: dotnet pack --configuration Release --p:Version=${{ steps.get_version.outputs.version }} --no-build --output ../../${{ env.PACKAGES_DIR }}

    - name: Upload Packages
      uses: actions/upload-artifact@v6
      with:
        name: nuget-packages
        path: ${{ env.PACKAGES_DIR }}

  publish:
    name: Publish NuGet Packages
    needs: build-and-pack
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
    - name: Download Packages
      uses: actions/download-artifact@v7
      with:
        name: nuget-packages
        path: ${{ env.PACKAGES_DIR }}

    - name: NuGet Login
      uses: NuGet/login@v1
      id: login
      with:
        user: ${{ secrets.NUGET_USERNAME }}

    - name: Push Packages
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        for pkg in ${{ env.PACKAGES_DIR }}/*.nupkg; do
          dotnet nuget push "$pkg" --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
        done

    - name: Push Symbols Packages
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        for sympkg in ${{ env.PACKAGES_DIR }}/*.snupkg; do
          dotnet nuget push "$sympkg" --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
        done
