# Publish Mathematics.NET NuGet Packages

name: Publish NuGet Packages
on:
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build and Publish NuGet Packages
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6

    - name: Set up .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          9.x
          10.x

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Mathematics.NET Project
      working-directory: src/Mathematics.NET
      run: dotnet build --configuration Release --no-restore

    - name: Pack Mathematics.NET
      working-directory: src/Mathematics.NET
      run: dotnet pack --configuration Release --p:Version=${{github.ref_name}} --no-build --output artifacts/packages/release

    - name: Build Mathematics.NET.SourceGenerators Project
      working-directory: src/Mathematics.NET.SourceGenerators
      run: dotnet build --configuration Release --no-restore

    - name: Pack Mathematics.NET.SourceGenerators
      working-directory: src/Mathematics.NET.SourceGenerators
      run: dotnet pack --configuration Release --p:Version=${{github.ref_name}} --no-build --output artifacts/packages/release

    - name: NuGet Login
      uses: NuGet/login@v1
      id: login
      with:
        user: ${{ secrets.NUGET_USERNAME }}

    - name: Push Packages
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        for pkg in artifacts/packages/release/*.nupkg; do
          dotnet nuget push "$pkg" --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
        done

    - name: Push Symbols Packages
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        for sympkg in artifacts/packages/release/*.snupkg; do
          dotnet nuget push "$sympkg" --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
        done
